import { StyleSheet } from "react-native";

import { Colors } from "../../constants/colors";

const styles = StyleSheet.create({
  game: {
    gap: 14,
  },
  heading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headingIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF2C6",
    borderWidth: 1,
    borderColor: "#EACB76",
  },
  headingCopy: {
    flex: 1,
  },
  eyebrow: {
    color: Colors.secondary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.1,
  },
  subtitle: {
    marginTop: 2,
    color: Colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  predictionLabel: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  roster: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  racerChoice: {
    width: "48.5%",
    minHeight: 58,
    padding: 9,
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFFDF7",
    borderWidth: 1.5,
    borderColor: "#DED8CA",
  },
  racerChoiceSelected: {
    backgroundColor: "#F2EEFF",
    borderColor: Colors.primary,
  },
  racerChoiceDisabled: {
    opacity: 0.72,
  },
  choiceAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  choiceCopy: {
    flex: 1,
  },
  choiceLetter: {
    color: Colors.textMuted,
    fontSize: 9,
    fontWeight: "900",
  },
  choiceName: {
    marginTop: 1,
    color: Colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  raceBoard: {
    padding: 12,
    gap: 8,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#E8F2DF",
    borderWidth: 1,
    borderColor: "#B7CDA7",
  },
  boardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  boardTitle: {
    color: "#49643C",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  finishLabel: {
    color: "#8B6A22",
    fontSize: 9,
    fontWeight: "900",
  },
  track: {
    position: "relative",
    height: 57,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.78)",
    borderWidth: 1,
    borderColor: "rgba(92,117,77,0.20)",
  },
  laneStripe: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 27,
    height: 1,
    backgroundColor: "rgba(80,104,66,0.12)",
  },
  finishLine: {
    position: "absolute",
    right: 43,
    top: 0,
    bottom: 0,
    width: 8,
    opacity: 0.22,
    backgroundColor: Colors.secondary,
  },
  runner: {
    position: "absolute",
    left: 4,
    top: 5,
    width: 46,
    alignItems: "center",
  },
  runnerAvatar: {
    width: 35,
    height: 35,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    shadowColor: "#25341F",
    shadowOpacity: 0.17,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  runnerName: {
    marginTop: 1,
    maxWidth: 58,
    color: "#405036",
    fontSize: 7,
    fontWeight: "900",
    textAlign: "center",
  },
  winnerBadge: {
    position: "absolute",
    right: 5,
    top: 17,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "#FFF0A9",
    borderWidth: 1,
    borderColor: "#DCB84C",
  },
  winnerText: {
    color: "#7C5A11",
    fontSize: 8,
    fontWeight: "900",
  },
  startButton: {
    minHeight: 50,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.secondary,
  },
  startButtonDisabled: {
    opacity: 0.42,
  },
  startButtonText: {
    color: Colors.surface,
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  runningStatus: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: "#F2EEFF",
    borderWidth: 1,
    borderColor: "#D8CFF6",
  },
  runningStatusText: {
    flex: 1,
    color: Colors.primary,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
});

export default styles;
