import { StyleSheet } from "react-native";

const GOLD = "#F7D77A";
const DEEP_GOLD = "#B77722";

export default StyleSheet.create({
  arch: {
    alignSelf: "center",
    borderColor: "rgba(247, 215, 122, 0.25)",
    borderRadius: 210,
    borderWidth: 2,
    height: "78%",
    position: "absolute",
    top: "9%",
    width: "115%",
  },
  archInset: {
    borderColor: "rgba(247, 215, 122, 0.09)",
    borderRadius: 200,
    borderWidth: 1,
    bottom: 8,
    left: 8,
    position: "absolute",
    right: 8,
    top: 8,
  },
  bottomGlow: {
    alignSelf: "center",
    backgroundColor: "rgba(24, 40, 59, 0.42)",
    borderRadius: 220,
    bottom: -150,
    height: 330,
    position: "absolute",
    width: 440,
  },
  brand: {
    color: GOLD,
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 4,
  },
  brandMark: {
    alignItems: "center",
    backgroundColor: "rgba(247, 215, 122, 0.08)",
    borderColor: "rgba(247, 215, 122, 0.38)",
    borderRadius: 18,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  eyebrow: {
    color: DEEP_GOLD,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 1.15,
    textAlign: "center",
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingTop: 10,
    zIndex: 4,
  },
  loadingCard: {
    alignSelf: "center",
    backgroundColor: "rgba(7, 11, 36, 0.76)",
    borderColor: "rgba(247, 215, 122, 0.27)",
    borderRadius: 20,
    borderWidth: 1,
    bottom: 24,
    maxWidth: 420,
    paddingHorizontal: 20,
    paddingVertical: 16,
    position: "absolute",
    width: "88%",
    zIndex: 5,
  },
  loadingHeading: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
    marginBottom: 12,
  },
  loadingText: {
    color: "#FFF4CF",
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
  },
  moonGlow: {
    backgroundColor: "rgba(255, 243, 200, 0.22)",
    borderRadius: 85,
    height: 170,
    position: "absolute",
    right: -35,
    top: 30,
    width: 170,
  },
  ornamentLine: {
    backgroundColor: "rgba(183, 119, 34, 0.56)",
    height: 1,
    width: 24,
  },
  ornamentRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    marginVertical: 4,
  },
  pageCopy: {
    alignItems: "center",
    paddingHorizontal: 8,
    position: "absolute",
    top: "43%",
    zIndex: 3,
  },
  progressFill: {
    backgroundColor: GOLD,
    borderRadius: 999,
    height: "100%",
    shadowColor: GOLD,
    shadowOpacity: 0.7,
    shadowRadius: 8,
  },
  progressTrack: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 999,
    height: 5,
    overflow: "hidden",
  },
  root: {
    flex: 1,
    overflow: "hidden",
  },
  safeArea: {
    flex: 1,
  },
  scene: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  subtitle: {
    color: "#6A471C",
    fontSize: 8,
    fontWeight: "700",
    lineHeight: 11,
    marginTop: 4,
    maxWidth: 128,
    textAlign: "center",
  },
  title: {
    color: "#27384D",
    fontSize: 21,
    fontWeight: "900",
    letterSpacing: 0.8,
    lineHeight: 23,
    textAlign: "center",
    textShadowColor: "rgba(183, 119, 34, 0.18)",
    textShadowOffset: { height: 1, width: 0 },
    textShadowRadius: 1,
  },
});
